[project]
name = "scrapy-curl-cffi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "curl-cffi>=0.12.0",
    "scrapy>=2.13.3",
]
